// Generated by CoffeeScript 1.6.3
var app, fn;

app = angular.module("remoteapp", ['ngRoute']);

app.config(["$routeProvider", function($routeProvider) {}]);

$("button").css("height", $("button").css("width"));

app.factory("socket", function() {
  var socket;
  socket = io.connect("http://192.168.1.111:3030");
  return socket;
});

console.log("working");

fn = function(s, r, l, socket) {
  s.snap = function() {
    return socket.emit("snap", "now");
  };
  s.flash = function() {
    return socket.emit("flash", "toggle");
  };
  socket.on("snapFinish", function(data) {
    return console.log(data);
  });
  socket.on("newImageExists", function(data) {
    return $("");
  });
  return s.id = l.path();
};

app.controller("mainCtrl", ["$scope", "$rootScope", "$location", "socket", fn]);

$(document).ready(function() {
  return setTimeout(function() {
    return $("#imgPreview").append('<img src="1.gif" alt=""/>');
  }, 10000);
});
