// Generated by CoffeeScript 1.6.3
var app, express, fs, io, lol;

io = require("socket.io").listen(3030);

express = require("express");

fs = require("fs");

app = new express();

app.use(express.bodyParser({
  keepExtensions: true,
  uploadDir: "uploads"
}));

app.use("/uploads", express["static"](__dirname + "/uploads"));

app.post("/upload", function(req, res) {
  console.log(req.files);
  console.log(req.files.file.path);
  return fs.rename(req.files.file.path, "uploads/abc.jpg", function(err) {
    if (err) {
      throw err;
    }
    console.log("change to tmp");
    return io.sockets.emit("newImageExists", {
      "reload": "now"
    });
  });
});

app.use("/", express["static"](__dirname + "/views"));

app.listen(80);

lol = {};

io.sockets.on("connection", function(s) {
  return s.on("snap", function() {
    s.broadcast.emit("takephoto", "now");
    return console.log("snap");
  });
});
